package com.example.graduationproject

object Constants {
    const val AR = "ar"
    const val EN = "en"
    const val FOODS_LIST = "FOODS_LIST"
    const val USER_LIST = "USER_LIST"
    const val FAMILIAR_NAME = "familiar_name"
    const val PRICE = "price"
    const val WALLET = "WALLET"
    const val WALLET_List = "WALLET_List"
    const val DESCRIPTION = "description"
    const val BALANCE = "BALANCE"
    const val IMAGE = "image"
    const val CURRENT_CHEF = "CURRENT_CHEF"
    const val FOOD_ID = "FOOD_ID"
    const val USER_ID = "USER_ID"
    const val QUANTITY = "quantity"
    const val FULL_NAME = "Full Name"
    const val Email = "Email"
    const val Phone = "Phone"
    const val PASSWORD = "Password"
    const val USER_TYPE = "USER_TYPE"
    const val ORDER_LIST = "ORDER_LIST"
    const val ORDER = "ORDER"
    const val User = "User"
    const val ORDER_ID = "ORDER_ID"
    const val INFO_USERS_SHARED_PREFS = "infoUsersSharedPrefs"
    const val ORDER_STATUS = "ORDER_STATUS"
    const val PAYMENT_METHOD = "PAYMENT_METHOD"
    const val OFFER_PRICE = "OFFER_PRICE"
    const val LATITUDE = "latitude"
    const val LONGITUDE = "longitude"
    const val REMEMBER_ME = "REMEMBER_ME"
}